### PR TITLE
Cheprasov/task products

### PR DESCRIPTION
**Pull request by AlexgorAlexgor**
/task products

### CODE REVIEW

**Review by Tatsiana-Kellermann — APPROVED** [review]

**Review by AlexgorAlexgor — COMMENTED** [review]
team3 commit

**Comment by AlexgorAlexgor** [comment]
https://github.com/MarinaNikole/Music.git

**Comment by AlexgorAlexgor** [comment]
https://github.com/MarinaNikole/Music.git

**Comment by AlexgorAlexgor** [comment]
team3 on Anton falshe PR

**Pull request closed without merging**
